/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MdU3YFbTYf4
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
        <div className="border border-gray-200 rounded-lg shadow-sm p-4 w-full">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex items-center justify-center rounded-lg border border-gray-200 border-dashed w-full aspect-square dark:border-gray-800">
              <div className="flex items-center justify-center w-full text-gray-500 text-sm">
                Drop your main image here
              </div>
            </div>
            <div className="flex items-center justify-center rounded-lg border border-gray-200 border-dashed w-full aspect-square dark:border-gray-800">
              <div className="flex items-center justify-center w-full text-gray-500 text-sm">
                Drop your tile images here
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-4">
          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-gray-500" htmlFor="grid-number">
              Grid Number
            </label>
            <Input id="grid-number" placeholder="0" />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-gray-500" htmlFor="output-width">
              Output Width (px)
            </label>
            <Input id="output-width" placeholder="250" />
          </div>
          <Button className="w-full" variant="outline">
            Generate Mosaic
          </Button>
        </div>
      </div>
      <div className="border border-gray-200 rounded-lg p-4">
        <div className="flex items-center justify-center h-[250px]">
          <div className="flex items-center justify-center w-full text-gray-500 text-sm">
            Your generated image will appear here
          </div>
        </div>
      </div>
    </div>
  )
}
